jobs:
- job: Windows

  pool:
    vmImage: 'windows-latest'

  steps:
  - task: BatchScript@1
    inputs:
      filename: 'EQDietCompiler.bat'
      arguments: '/compile'
    displayName: 'Building class files through EQDiet Compiler'

  - task: BatchScript@1
    inputs:
      filename: 'EQDietCompiler.bat'
      arguments: '/jar'
    displayName: 'Building JAR file through EQDiet Compiler'

  - task: BatchScript@1
    inputs:
      filename: 'EQDietCompiler.bat'
      arguments: '/launch4j'
    displayName: 'Test: Trying to install Launch4j through EQDiet Compiler'

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(Pipeline.Workspace)\s\Release\EQDietDownloader.jar'
      artifact: 'EQDiet Downloader JAR file'
      publishLocation: 'pipeline'
    displayName: 'Publishing Pipeline Artifacts'
