jobs:
- job: Windows

  pool:
    vmImage: 'windows-latest'

  steps:
  - script: EQDietCompiler.bat /compile
    displayName: 'Building class files through EQDiet Compiler'

  - script: EQDietCompiler.bat /jar
    displayName: 'Building JAR file through EQDiet Compiler'
  
  - script: EQDietCompiler.bat /launch4j
    displayName: 'Test: Trying to install Launch4j through EQDiet Compiler'

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(Pipeline.Workspace)\s\Release\EQDietDownloader.jar'
      artifact: 'EQDiet Downloader 1.0 JAR file'
      publishLocation: 'pipeline'
    displayName: 'Publishing Pipeline Artifacts'
