# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java Compiler (Javac)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with javac
      run: javac -verbose EQDietDownloader1.0-src/src/EQDietDownloader.javant
      run: cd EQDietDownloader1.0-src && mkdir Build && cp src/net/jimmc/jShortcut/*.* Build/net/jimmc/jShortcut/ && cp src/*.dll Build/ && cp src/EQDietDownloader.class Build/ && cd Build
    - name: Build JAR file
      run: 
